server:
  port: 8080
  servlet:
    context-path:
spring:
  application:
    name: Challenge_7
  datasource:
    url: "jdbc:mysql://localhost:3306/challenge7"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
openapi:
  service:
    api-docs: api-services
    server: http://localhost:8080/
    title: Product API
    version: 1.0.0
jwt:
  signerKey: "dsFyyenVljBLPSWeaQWcX0g/7VnnKrEcWXY9JXsdjaKy44o+aj1VBKeU8H+N2rrz"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


